#!/usr/bin/env ruby
require 'timing_attack'
require 'optparse'
require 'json'

options = {}
opt_parser = OptionParser.new do |opts|
  opts.program_name = File.basename(__FILE__)
  opts.banner = "#{opts.program_name} [options] -u <target> <inputs>"
  opts.on("-u URL", "--url URL", "URL of endpoint to profile") { |str| options[:url] = str }
  opts.on("-n NUM", "--number NUM", "Requests per input (default: 50)") do |num|
    options[:iterations] = num.to_i
  end
  opts.on("-c NUM", "--concurrency NUM", "Number of concurrent requests (default: 15)") do |num|
    options[:concurrency] = num.to_i
  end
  opts.on("-t NUM", "--threshold NUM", "Minimum threshold, in seconds, for meaningfulness (default: 0.025)") do |num|
    options[:threshold] = num.to_f
  end
  opts.on("-p", "--post", "Use POST, not GET") { |bool| options[:method] = bool ? :post : :get }
  opts.on("-q", "--quiet", "Quiet mode (don't display progress bars)") { |bool| options[:verbose] = !bool }
  opts.on("--brute_force", "Brute force mode") { |bool| options[:brute_force] = bool }
  opts.on("--parameters STR", "JSON hash of parameters.  'INPUT' will be replaced with the attack string") do |str|
    options[:params] = JSON.parse(str)
  end
  opts.on("--body STR", "JSON of body paramets to be sent to Typhoeus.  'INPUT' will be replaced with the attack string") do |str|
    options[:body] = JSON.parse(str)
  end
  opts.on("--percentile NUM", "Use NUMth percentile for calculations (default: 3)") { |num| options[:percentile] = num.to_i }
  opts.on("--mean", "Use mean for calculations") { |bool| options[:mean] = bool }
  opts.on("--median", "Use median for calculations") { |bool| options[:median] = bool }
  opts.on_tail("-v", "--version", "Print version information") do
    gem = Gem::Specification.find_by_name('timing_attack')
    puts "#{gem.name} #{gem.version}"
    exit
  end
  opts.on_tail("-h", "--help", "Display this screen") { puts opts ; exit }
end

begin
  opt_parser.parse!
rescue OptionParser::InvalidOption => e
  STDERR.puts e.message
  puts opt_parser
  exit
end
options[:verbose] = true if options[:verbose].nil?
if options[:percentile]
  options.delete(:mean)
elsif options[:median]
  options[:percentile] = 50
elsif options[:mean]
  options.delete(:percentile)
end

begin
  atk = if options.delete(:brute_force)
          TimingAttack::BruteForcer.new(options: options)
        else
          TimingAttack::Enumerator.new(inputs: ARGV, options: options)
        end
  atk.run!
rescue ArgumentError => e
  STDERR.puts e.message
  puts opt_parser
  exit
rescue Interrupt => e
  puts "\nCaught interrupt, exiting"
  exit
end
